import type { Metadata } from "next";
import pretendard from "@/fonts/pretendard";
import "@/styles/globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="font-sans">
        <div id="wrapper">
          <Header />
          <section id="contents">{children}</section>
          <Footer />
        </div>
      </body>
    </html>
  );
}
