import type { Metadata } from "next";
import "@/styles/globals.css";
import pretendard from "@/fonts/pretendard";
import { cookies } from "next/headers";
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import AuthStoreProvider from "@/providers/AuthStoreProvider";
import Header from "@/components/ui/Header";
import { ToastProvider } from "@/components/ui/Toast";
import RootClientWrapper from "@/providers/RootClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(
          cookiesToSet: {
            name: string;
            value: string;
            options: CookieOptions;
          }[]
        ) {
          try {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options);
            });
          } catch {}
        },
      },
    }
  );

  const {
    data: { user: authUser },
  } = await supabase.auth.getUser();

  let initialEmployee: unknown | null = null;

  if (authUser?.id) {
    const { data } = await supabase
      .from("employees_with_unused")
      .select("*")
      .eq("user_id", authUser.id)
      .maybeSingle();

    initialEmployee = data ?? null;
  }

  return (
    <html lang="ko" className={pretendard.variable}>
      <body>
        <ToastProvider>
          <AuthStoreProvider
            initialUser={authUser ?? null}
            initialEmployee={initialEmployee}
          >
            <RootClientWrapper>
              <div id="wrapper">
                <Header />
                <section id="contents">{children}</section>
              </div>
            </RootClientWrapper>
          </AuthStoreProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
